import { Open_Sans } from "next/font/google";
import "./globals.css";
import Providers from "../app/providers"; 
import MSWProvider from "./MSWProvider";
import "./mswInit";

const openSans = Open_Sans({
  subsets: ["latin"],
  variable: "--font-open-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={openSans.variable}>
        <MSWProvider/>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}